name: counter
description: Counter feature module
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  injecteo: ^1.0.0
  logger:
    path: ../logger

dev_dependencies:
  build_runner: ^2.3.2
  injecteo_generator: ^1.0.0
  linteo: ^1.1.0
  test: ^1.16.0
