name: counter
description: Counter feature module
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  injecteo:
    path: ../../../../packages/injecteo
  logger:
    path: ../logger

dev_dependencies:
  build_runner: ^2.3.2
  injecteo_generator:
    path: ../../../../packages/injecteo_generator
  lints: ^2.0.0
  test: ^1.16.0
