name: di_example
description: Example how to use injecteo in Flutter application
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  fimber: ^0.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  hooked_bloc: ^1.2.1
  injecteo: ^1.0.0

  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injecteo_generator: ^1.0.0
  json_serializable: ^6.5.3
  linteo: ^1.1.0

flutter:
  uses-material-design: true
