name: di_example
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  injecteo:
    path: ../../packages/injecteo
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  hooked_bloc: ^1.2.1
  flutter_hooks: ^0.18.5+1
  shared_preferences: ^2.0.15
  fimber: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  injecteo_generator:
    path: ../../packages/injecteo_generator

  flutter_lints: ^2.0.0
  freezed: ^2.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true
