name: injecteo_models
description: Only for injecteo internal models generation
version: 1.0.0
repository: https://github.com/Iteo/injecteo
issue_tracker: https://github.com/Iteo/injecteo/issues
homepage: https://github.com/Iteo/injecteo
documentation: https://github.com/Iteo/injecteo/blob/main/packages/injecteo/README.md 

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  linteo: ^1.1.0
