name: feature_packages
description: A sample command-line application with feature packages architecture
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  counter: # comes from local package, see path in pubspec_overrides.yaml
  injecteo: ^1.0.0
  logger: # comes from local package, see path in pubspec_overrides.yaml

dev_dependencies:
  linteo: ^1.1.0
  test: ^1.16.0
