name: feature_packages
description: A sample command-line application with feature packages architecture
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  counter:
    path: packages/counter
  injecteo:
    path: ../../packages/injecteo
  logger:
    path: packages/logger

dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0
