name: example
description: Example how to generate DI with injecteo_generator
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  injecteo: ^1.0.0
dev_dependencies:
  build_runner: ^2.1.10
  injecteo_generator: ^1.0.1
  lints: ^1.0.0
