include: package:linteo/analysis_options.yaml
analyzer:
  language:
    strict-casts: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    parameter_assignments: warning
    body_might_complete_normally_nullable: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    always_use_package_imports: false
    sort_constructors_first: true
    comment_references: false
    only_throw_errors: false
