builders:
  injecteo_builder:
    import: "package:injecteo_generator/dependency_builder.dart"
    builder_factories: ["dependencyBuilder"]
    build_extensions: { ".dart": [".injecteo.json"] }
    auto_apply: dependents
    runs_before: ["injecteo_generator|injecteo_initializer_builder"]
    build_to: cache
  injecteo_initializer_builder:
    import: "package:injecteo_generator/initializer_builder.dart"
    builder_factories: ["initializerBuilder"]
    build_extensions: { ".dart": [".config.dart"] }
    auto_apply: dependents
    build_to: source
