builders:
  injecteo_dependency_builder:
    import: "package:injecteo_generator/builder.dart"
    builder_factories: ["dependencyGeneratorBuilder"]
    build_extensions: { ".dart": [".injecteo.json"] }
    auto_apply: dependents
    build_to: cache
    runs_before: [":injecteo_builder"]
  injecteo_builder:
    import: "package:injecteo_generator/builder.dart"
    builder_factories: ["initializerBuilder"]
    build_extensions: { ".dart": [".config.dart"] }
    auto_apply: dependents
    build_to: source
