name: injecteo_generator
description: A new Flutter package project.
version: 0.0.1
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^5.1.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.21.6
