name: injecteo_generator
description: Generator for injecteo package.
version: 1.0.1
repository: https://github.com/Iteo/injecteo
issue_tracker: https://github.com/Iteo/injecteo/issues
homepage: https://github.com/Iteo/injecteo
documentation: https://github.com/Iteo/injecteo/blob/main/packages/injecteo/README.md 

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  code_builder: ^4.3.0
  collection: ^1.16.0
  dart_style: ^2.2.4
  freezed_annotation: ^2.2.0
  glob: ^2.1.0

  injecteo: ^1.0.0
  injecteo_models: ^1.0.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  path: ^1.8.2
  source_gen: ^1.2.6
  source_helper: ^1.3.3

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  crypto: ^3.0.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  linteo: ^1.1.0
  source_gen_test: ^1.0.4
  test: ^1.21.6
