name: injecteo_generator
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  code_builder: ^4.3.0
  collection: ^1.16.0
  dart_style: ^2.2.4
  freezed_annotation: ^2.2.0
  glob: ^2.1.0

  injecteo:
    path: ../injecteo
  injecteo_models:
    path: ../injecteo_models

  json_annotation: ^4.7.0
  meta: ^1.8.0
  path: ^1.8.2
  source_gen: ^1.2.6
  source_helper: ^1.3.3

dev_dependencies:
  build_runner: ^2.3.2
  crypto: ^3.0.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lint: ^1.10.0
  source_gen_test: ^1.0.4
  test: ^1.21.6
