name: _internal
description: Only for internal Freezed models generation
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
