name: injecteo
description: Service locator for IoC pattern. Export annotations and abstract classes used by injecteo_generator.
version: 1.0.0
repository: https://github.com/Iteo/injecteo
issue_tracker: https://github.com/Iteo/injecteo/issues
homepage: https://github.com/Iteo/injecteo
documentation: https://github.com/Iteo/injecteo/blob/develop/packages/injecteo/README.md 

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  get_it: ^7.2.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.21.6
